name: iamngoni_co
description: "Ngonidzashe Mangudya"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-135.0.dev <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  candlesticks:
  carousel_slider:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_frame: ^1.1.0
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  handy_extensions: ^0.1.6
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  localregex:
  lottie: ^2.7.0
  modal_bottom_sheet: ^3.0.0-pre
  network_info_plus: ^4.0.2
  permission_handler:
  pretty_dio_logger: ^1.3.1
  relative_scale: ^2.0.0
  sentry_dio: ^7.10.1
  sentry_flutter: ^7.10.1
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_native_splash: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator:
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/

    # lingua
    - assets/lingua/letters/

    # parkade
    - assets/parkade/icons/
    - assets/parkade/images/

    # marketstack
    - assets/market/images/

    # shopperschoice
    - assets/shopperschoice/images/
    - assets/shopperschoice/icons/

  fonts:
    - family: HedvigLettersSerif
      fonts:
        - asset: fonts/HedvigLettersSerif-Regular.ttf
