/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThoughtsImport } from './routes/thoughts'
import { Route as BlogImport } from './routes/blog'
import { Route as IndexImport } from './routes/index'
import { Route as ThoughtsIndexImport } from './routes/thoughts.index'
import { Route as BlogIndexImport } from './routes/blog.index'
import { Route as ThoughtsSlugImport } from './routes/thoughts.$slug'
import { Route as BlogSlugImport } from './routes/blog.$slug'

// Create/Update Routes

const ThoughtsRoute = ThoughtsImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThoughtsIndexRoute = ThoughtsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThoughtsRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)

const ThoughtsSlugRoute = ThoughtsSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThoughtsRoute,
} as any)

const BlogSlugRoute = BlogSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsImport
      parentRoute: typeof rootRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugImport
      parentRoute: typeof BlogImport
    }
    '/thoughts/$slug': {
      id: '/thoughts/$slug'
      path: '/$slug'
      fullPath: '/thoughts/$slug'
      preLoaderRoute: typeof ThoughtsSlugImport
      parentRoute: typeof ThoughtsImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogImport
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof ThoughtsIndexImport
      parentRoute: typeof ThoughtsImport
    }
  }
}

// Create and export the route tree

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ThoughtsRouteChildren {
  ThoughtsSlugRoute: typeof ThoughtsSlugRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
}

const ThoughtsRouteChildren: ThoughtsRouteChildren = {
  ThoughtsSlugRoute: ThoughtsSlugRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
}

const ThoughtsRouteWithChildren = ThoughtsRoute._addFileChildren(
  ThoughtsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/thoughts': typeof ThoughtsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/thoughts'
    | '/blog/$slug'
    | '/thoughts/$slug'
    | '/blog/'
    | '/thoughts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/thoughts/$slug' | '/blog' | '/thoughts'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/thoughts'
    | '/blog/$slug'
    | '/thoughts/$slug'
    | '/blog/'
    | '/thoughts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ThoughtsRoute: typeof ThoughtsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ThoughtsRoute: ThoughtsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/thoughts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx",
      "children": [
        "/blog/$slug",
        "/blog/"
      ]
    },
    "/thoughts": {
      "filePath": "thoughts.tsx",
      "children": [
        "/thoughts/$slug",
        "/thoughts/"
      ]
    },
    "/blog/$slug": {
      "filePath": "blog.$slug.tsx",
      "parent": "/blog"
    },
    "/thoughts/$slug": {
      "filePath": "thoughts.$slug.tsx",
      "parent": "/thoughts"
    },
    "/blog/": {
      "filePath": "blog.index.tsx",
      "parent": "/blog"
    },
    "/thoughts/": {
      "filePath": "thoughts.index.tsx",
      "parent": "/thoughts"
    }
  }
}
ROUTE_MANIFEST_END */
