/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PoetryImport } from './routes/poetry'
import { Route as BlogImport } from './routes/blog'
import { Route as IndexImport } from './routes/index'
import { Route as PoetryIndexImport } from './routes/poetry.index'
import { Route as BlogIndexImport } from './routes/blog.index'
import { Route as PoetrySlugImport } from './routes/poetry.$slug'
import { Route as BlogSlugImport } from './routes/blog.$slug'

// Create/Update Routes

const PoetryRoute = PoetryImport.update({
  id: '/poetry',
  path: '/poetry',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PoetryIndexRoute = PoetryIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoetryRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)

const PoetrySlugRoute = PoetrySlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PoetryRoute,
} as any)

const BlogSlugRoute = BlogSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/poetry': {
      id: '/poetry'
      path: '/poetry'
      fullPath: '/poetry'
      preLoaderRoute: typeof PoetryImport
      parentRoute: typeof rootRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugImport
      parentRoute: typeof BlogImport
    }
    '/poetry/$slug': {
      id: '/poetry/$slug'
      path: '/$slug'
      fullPath: '/poetry/$slug'
      preLoaderRoute: typeof PoetrySlugImport
      parentRoute: typeof PoetryImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogImport
    }
    '/poetry/': {
      id: '/poetry/'
      path: '/'
      fullPath: '/poetry/'
      preLoaderRoute: typeof PoetryIndexImport
      parentRoute: typeof PoetryImport
    }
  }
}

// Create and export the route tree

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PoetryRouteChildren {
  PoetrySlugRoute: typeof PoetrySlugRoute
  PoetryIndexRoute: typeof PoetryIndexRoute
}

const PoetryRouteChildren: PoetryRouteChildren = {
  PoetrySlugRoute: PoetrySlugRoute,
  PoetryIndexRoute: PoetryIndexRoute,
}

const PoetryRouteWithChildren =
  PoetryRoute._addFileChildren(PoetryRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/poetry': typeof PoetryRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/poetry/$slug': typeof PoetrySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/poetry/': typeof PoetryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/poetry/$slug': typeof PoetrySlugRoute
  '/blog': typeof BlogIndexRoute
  '/poetry': typeof PoetryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/poetry': typeof PoetryRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/poetry/$slug': typeof PoetrySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/poetry/': typeof PoetryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/poetry'
    | '/blog/$slug'
    | '/poetry/$slug'
    | '/blog/'
    | '/poetry/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/poetry/$slug' | '/blog' | '/poetry'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/poetry'
    | '/blog/$slug'
    | '/poetry/$slug'
    | '/blog/'
    | '/poetry/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  PoetryRoute: typeof PoetryRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  PoetryRoute: PoetryRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/poetry"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx",
      "children": [
        "/blog/$slug",
        "/blog/"
      ]
    },
    "/poetry": {
      "filePath": "poetry.tsx",
      "children": [
        "/poetry/$slug",
        "/poetry/"
      ]
    },
    "/blog/$slug": {
      "filePath": "blog.$slug.tsx",
      "parent": "/blog"
    },
    "/poetry/$slug": {
      "filePath": "poetry.$slug.tsx",
      "parent": "/poetry"
    },
    "/blog/": {
      "filePath": "blog.index.tsx",
      "parent": "/blog"
    },
    "/poetry/": {
      "filePath": "poetry.index.tsx",
      "parent": "/poetry"
    }
  }
}
ROUTE_MANIFEST_END */
